# Site settings
title: Alex' Blog
email: blog@alexanderkennedy.com
description: > # this means to ignore newlines until "baseurl:"
  Alex Kennedy is an artist, writer, and assembler of odd things, hailing from Vancouver, BC.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://alexanderkennedy.com" # the base hostname & protocol for your site
twitter_username: sourcescited
github_username:  alexanderkennedy

# Build settings
markdown: kramdown
